/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "inverse-primary": "#bec6e0",
        "on-primary-container": "#7c839b",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-fixed-variant": "#004c6e",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-container": "#e5eeff",
        "error": "#ba1a1a",
        "outline": "#76777d",
        "primary": "#000000",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#008cc7",
        "tertiary-container": "#001e2f",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#fefcff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#45464d",
        "background": "#f8f9ff",
        "on-primary-fixed": "#131b2e",
        "on-background": "#0b1c30",
        "secondary-container": "#316bf3",
        "outline-variant": "#c6c6cd",
        "surface-container-low": "#eff4ff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary": "#000000",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#89ceff",
        "on-secondary-fixed": "#00174b",
        "surface-tint": "#565e74",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#001e2f",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9ff",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#c9e6ff",
        "secondary": "#0051d5",
        "secondary-fixed": "#dbe1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "margin": "2rem",
        "space-xl": "2rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "title-sm": ["Plus Jakarta Sans"],
        "display-xl-mobile": ["Plus Jakarta Sans"],
        "body-md-medium": ["Manrope"],
        "metric-numeral": ["Plus Jakarta Sans"],
        "body-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "caption-xs": ["Manrope"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Manrope"],
        "display-xl": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg-mobile": ["1.5rem", { "lineHeight": "1.3", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "title-sm": ["1.125rem", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-xl-mobile": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md-medium": ["0.875rem", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "500" }],
        "metric-numeral": ["1.875rem", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["0.875rem", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["1rem", { "lineHeight": "1.55", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "caption-xs": ["0.6875rem", { "lineHeight": "1.35", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["1.375rem", { "lineHeight": "1.35", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-lg": ["2rem", { "lineHeight": "1.25", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["0.75rem", { "lineHeight": "1.4", "letterSpacing": "0.025em", "fontWeight": "600" }],
        "display-xl": ["3rem", { "lineHeight": "1.15", "letterSpacing": "-0.025em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
